# Generated by Django 2.2.5 on 2022-12-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20221206_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
    ]
