# Generated by Django 2.2.5 on 2022-12-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20221206_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='label',
        ),
    ]
