# Generated by Django 2.2.5 on 2022-12-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_song_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_lyrics',
            field=models.CharField(default='', max_length=2000, verbose_name='歌曲文件'),
        ),
    ]
